In [89]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [90]:
df=pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [92]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

***Features aur Target alag karo***

In [93]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [94]:
print(X)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]

In [95]:
print(y)

[16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]

***Encoding variables***

In [96]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

le1=LabelEncoder()
le2=LabelEncoder()
X[:,1]=le1.fit_transform(X[:,1])
X[:,4]=le2.fit_transform(X[:,4])

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(drop='first'),[5])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [97]:
print(X)

[[0.0 0.0 1.0 ... 27.9 0 1]
 [0.0 1.0 0.0 ... 33.77 1 0]
 [0.0 1.0 0.0 ... 33.0 3 0]
 ...
 [0.0 1.0 0.0 ... 36.85 0 0]
 [0.0 0.0 1.0 ... 25.8 0 0]
 [1.0 0.0 0.0 ... 29.07 0 1]]

***Train-Test Split***

In [98]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [99]:
y_train.shape

(1003,)

In [100]:
X_train.shape

(1003, 8)

In [101]:
y_test.shape

(335,)

***Feature Scaling***

In [102]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train[:, [4, 6]] = ss.fit_transform(X_train[:, [4, 6]])
X_test[:, [4, 6]] = ss.transform(X_test[:, [4, 6]])

print(X_train)

[[0.0 1.0 0.0 ... 29.59 -0.06360656793383669 0]
 [0.0 0.0 0.0 ... 22.04 -0.892144069721345 0]
 [0.0 0.0 1.0 ... 24.6 -0.06360656793383669 0]
 ...
 [0.0 1.0 0.0 ... 25.08 -0.892144069721345 0]
 [1.0 0.0 0.0 ... 35.53 -0.892144069721345 0]
 [0.0 0.0 1.0 ... 18.5 -0.06360656793383669 0]]

In [104]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [113]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1.11e+04 9.72e+03]
 [9.37e+03 8.55e+03]
 [3.83e+04 4.57e+04]
 [1.63e+04 1.30e+04]
 [7.04e+03 9.64e+03]
 [4.10e+03 4.50e+03]
 [1.73e+03 2.20e+03]
 [1.45e+04 1.14e+04]
 [9.17e+03 7.54e+03]
 [7.72e+03 5.43e+03]
 [4.63e+03 6.75e+03]
 [1.04e+04 1.05e+04]
 [8.76e+03 7.34e+03]
 [3.74e+03 4.19e+03]
 [2.82e+04 1.83e+04]
 [1.06e+04 1.07e+04]
 [1.14e+04 1.25e+04]
 [6.25e+03 3.49e+03]
 [8.42e+03 6.46e+03]
 [2.74e+04 3.35e+04]
 [3.38e+04 2.40e+04]
 [1.44e+04 1.26e+04]
 [1.18e+04 2.30e+04]
 [3.21e+04 2.31e+04]
 [4.15e+03 1.67e+03]
 [9.36e+03 4.67e+03]
 [1.23e+03 3.73e+03]
 [9.71e+03 7.68e+03]
 [3.71e+03 3.76e+03]
 [1.06e+04 8.41e+03]
 [9.16e+03 8.06e+03]
 [4.00e+04 4.90e+04]
 [1.56e+04 1.30e+04]
 [1.38e+04 2.06e+04]
 [2.50e+04 1.46e+04]
 [5.27e+03 4.14e+03]
 [1.25e+04 8.35e+03]
 [3.08e+04 5.12e+04]
 [3.37e+04 4.00e+04]
 [3.69e+03 1.88e+03]
 [4.08e+03 5.46e+03]
 [3.96e+03 2.87e+03]
 [3.07e+04 2.01e+04]
 [3.96e+04 4.75e+04]
 [2.78e+04 3.61e+04]
 [5.30e+03 2.60e+04]
 [1.05e+04 1.97e+04]
 [8.00e+03 6.94e+03]
 [3.72e+03 4.72e+03]
 [1.01e+04 2.22e+04]
 [5.83e+03 2.90e+03]
 [3.66e+03 1.88e+04]
 [3.30e+04 2.36e+04]
 [3.86e+04 4.63e+04]
 [1.59e+04 2.42e+04]
 [7.29e+03 3.27e+03]
 [5.70e+03 2.32e+03]
 [9.59e+03 8.83e+03]
 [8.87e+03 1.45e+04]
 [1.18e+04 1.31e+04]
 [1.92e+03 1.25e+03]
 [3.91e+04 4.67e+04]
 [1.48e+04 1.39e+04]
 [1.18e+04 9.63e+03]
 [1.41e+04 1.07e+04]
 [1.40e+04 9.88e+03]
 [2.59e+04 3.25e+04]
 [3.25e+04 3.87e+04]
 [8.14e+02 3.18e+03]
 [1.03e+04 8.16e+03]
 [1.23e+04 1.30e+04]
 [1.14e+04 1.16e+04]
 [2.54e+04 1.62e+04]
 [1.54e+04 1.39e+04]
 [1.13e+04 1.30e+04]
 [1.27e+04 1.32e+04]
 [6.54e+03 7.15e+03]
 [9.51e+03 7.73e+03]
 [3.03e+04 2.03e+04]
 [3.91e+04 4.74e+04]
 [1.21e+04 1.17e+04]
 [3.72e+04 4.59e+04]
 [4.49e+03 2.06e+03]
 [9.37e+03 7.44e+03]
 [3.50e+04 4.10e+04]
 [2.89e+04 1.90e+04]
 [8.67e+03 3.41e+03]
 [5.14e+03 2.70e+03]
 [1.20e+04 1.23e+04]
 [3.05e+04 3.68e+04]
 [1.02e+04 6.33e+03]
 [1.13e+04 1.02e+04]
 [8.49e+03 1.79e+04]
 [8.80e+03 8.52e+03]
 [8.54e+03 4.52e+03]
 [7.42e+03 5.15e+03]
 [3.61e+04 4.23e+04]
 [3.32e+04 3.90e+04]
 [7.83e+03 5.33e+03]
 [1.50e+04 1.06e+04]
 [4.00e+03 1.82e+03]
 [9.00e+03 5.38e+03]
 [6.27e+03 4.35e+03]
 [3.15e+04 3.77e+04]
 [3.32e+04 3.28e+04]
 [2.18e+03 3.35e+03]
 [8.98e+03 1.06e+04]
 [6.86e+03 3.56e+03]
 [1.46e+04 1.19e+04]
 [3.72e+04 5.26e+04]
 [1.03e+04 1.25e+04]
 [1.05e+04 4.27e+03]
 [1.03e+04 9.25e+03]
 [2.72e+04 3.37e+04]
 [3.98e+04 4.87e+04]
 [8.57e+03 7.73e+03]
 [3.83e+02 1.96e+03]
 [8.98e+03 8.44e+03]
 [1.52e+04 1.23e+04]
 [9.70e+03 9.30e+03]
 [3.51e+04 4.21e+04]
 [7.39e+03 9.99e+03]
 [1.68e+04 1.43e+04]
 [9.78e+03 5.43e+03]
 [8.21e+03 7.63e+03]
 [3.15e+03 4.91e+03]
 [3.30e+04 2.34e+04]
 [3.17e+04 2.11e+04]
 [3.96e+04 4.82e+04]
 [5.82e+03 1.92e+03]
 [9.21e+03 8.22e+03]
 [3.59e+03 1.73e+03]
 [7.56e+03 5.98e+03]
 [8.70e+03 9.36e+03]
 [3.18e+04 2.21e+04]
 [3.00e+04 3.55e+04]
 [2.98e+04 1.95e+04]
 [8.62e+03 1.01e+04]
 [3.24e+04 2.32e+04]
 [3.60e+03 2.79e+03]
 [3.91e+03 2.26e+03]
 [1.13e+04 1.06e+04]
 [1.30e+04 9.30e+03]
 [1.29e+04 1.04e+04]
 [5.65e+03 4.89e+03]
 [1.54e+04 1.43e+04]
 [1.48e+04 2.83e+04]
 [2.63e+03 1.44e+04]
 [2.84e+02 1.63e+03]
 [1.09e+04 2.55e+04]
 [7.50e+03 6.56e+03]
 [3.18e+04 3.96e+04]
 [1.24e+04 9.96e+03]
 [2.35e+03 1.72e+03]
 [6.67e+03 2.73e+03]
 [7.76e+03 6.50e+03]
 [4.68e+03 2.64e+03]
 [2.13e+03 1.72e+03]
 [1.15e+04 1.11e+04]
 [1.27e+04 1.01e+04]
 [7.42e+03 4.85e+03]
 [1.62e+04 1.30e+04]
 [1.19e+04 2.89e+04]
 [1.40e+04 9.39e+03]
 [3.30e+03 4.54e+03]
 [7.46e+03 1.71e+04]
 [2.32e+04 1.38e+04]
 [7.71e+03 6.11e+03]
 [5.63e+03 4.44e+03]
 [5.16e+03 1.63e+03]
 [6.97e+03 4.06e+03]
 [5.35e+03 4.44e+03]
 [1.01e+04 8.31e+03]
 [5.35e+03 1.99e+03]
 [5.79e+03 4.26e+03]
 [6.64e+03 4.50e+03]
 [3.87e+03 4.43e+03]
 [5.76e+03 6.12e+03]
 [3.82e+04 3.02e+04]
 [1.68e+03 1.71e+03]
 [1.27e+04 1.12e+04]
 [9.15e+03 6.80e+03]
 [1.39e+04 1.14e+04]
 [5.37e+03 2.50e+03]
 [5.34e+03 2.74e+04]
 [3.65e+04 2.81e+04]
 [4.55e+03 2.25e+03]
 [2.09e+03 2.60e+03]
 [1.53e+04 1.47e+04]
 [1.27e+04 1.04e+04]
 [3.52e+04 4.11e+04]
 [4.74e+03 3.98e+03]
 [5.67e+03 5.47e+03]
 [3.12e+04 2.12e+04]
 [6.41e+03 2.53e+03]
 [2.21e+03 1.97e+03]
 [8.56e+03 6.41e+03]
 [1.01e+04 6.55e+03]
 [7.96e+03 4.06e+03]
 [6.01e+03 4.24e+03]
 [1.32e+04 1.15e+04]
 [3.84e+04 4.69e+04]
 [1.38e+04 1.23e+04]
 [2.90e+04 1.92e+04]
 [7.00e+03 4.43e+03]
 [3.54e+04 4.30e+04]
 [3.94e+03 2.32e+04]
 [1.18e+04 9.14e+03]
 [8.97e+03 5.84e+03]
 [6.23e+03 1.15e+03]
 [1.15e+04 8.77e+03]
 [1.45e+04 1.40e+04]
 [5.37e+03 5.31e+03]
 [4.48e+03 1.08e+04]
 [7.90e+03 6.28e+03]
 [1.41e+03 1.97e+03]
 [7.99e+03 6.75e+03]
 [4.54e+03 5.35e+03]
 [1.27e+04 1.40e+04]
 [4.36e+03 6.88e+03]
 [1.01e+04 6.20e+03]
 [7.30e+03 7.99e+03]
 [9.23e+03 8.28e+03]
 [2.54e+03 3.21e+03]
 [1.31e+04 1.18e+04]
 [1.69e+04 1.42e+04]
 [1.48e+04 1.23e+04]
 [1.05e+04 1.18e+04]
 [5.27e+03 6.65e+03]
 [2.23e+03 2.14e+03]
 [1.94e+03 1.13e+03]
 [1.36e+04 8.34e+03]
 [1.39e+04 1.22e+04]
 [5.18e+03 4.56e+03]
 [3.71e+03 1.76e+04]
 [9.48e+03 6.88e+03]
 [1.00e+04 9.45e+03]
 [2.85e+04 3.43e+04]
 [7.76e+03 6.07e+03]
 [1.05e+04 1.17e+04]
 [6.30e+03 5.38e+03]
 [3.01e+04 3.75e+04]
 [1.11e+04 7.37e+03]
 [7.58e+03 7.33e+03]
 [1.04e+04 8.41e+03]
 [1.24e+04 1.05e+04]
 [3.19e+03 3.28e+03]
 [1.10e+04 7.73e+03]
 [1.69e+03 2.73e+03]
 [7.15e+03 6.86e+03]
 [2.84e+04 1.95e+04]
 [3.86e+04 4.73e+04]
 [6.38e+03 3.99e+03]
 [8.12e+03 3.24e+03]
 [2.68e+03 7.32e+03]
 [6.39e+02 1.70e+03]
 [1.05e+04 7.45e+03]
 [4.17e+03 1.63e+03]
 [5.20e+03 4.88e+03]
 [2.31e+03 3.56e+03]
 [6.76e+03 8.61e+03]
 [3.34e+04 2.45e+04]
 [3.83e+04 4.57e+04]
 [1.48e+04 1.50e+04]
 [8.45e+03 6.66e+03]
 [1.62e+04 2.07e+04]
 [3.29e+04 4.09e+04]
 [9.57e+03 9.50e+03]
 [3.37e+04 4.02e+04]
 [3.37e+03 1.14e+03]
 [3.10e+04 3.85e+04]
 [8.23e+03 4.67e+03]
 [1.42e+04 1.30e+04]
 [4.33e+03 4.19e+03]
 [3.22e+04 3.87e+04]
 [8.49e+03 5.59e+03]
 [1.11e+04 2.73e+04]
 [8.96e+03 9.79e+03]
 [4.52e+03 2.36e+03]
 [1.26e+04 1.32e+04]
 [1.18e+04 1.22e+04]
 [8.72e+03 4.32e+03]
 [1.34e+04 1.27e+04]
 [3.00e+03 2.20e+03]
 [1.08e+04 6.08e+03]
 [5.58e+03 3.59e+03]
 [1.08e+04 8.60e+03]
 [3.17e+04 2.18e+04]
 [9.85e+03 2.93e+03]
 [1.46e+03 1.71e+03]
 [7.89e+02 2.80e+03]
 [3.99e+04 4.85e+04]
 [9.79e+03 9.28e+03]
 [7.36e+03 4.74e+03]
 [1.41e+04 1.23e+04]
 [1.35e+04 1.19e+04]
 [2.75e+04 3.42e+04]
 [7.17e+03 6.50e+03]
 [6.97e+03 4.75e+03]
 [1.22e+04 8.46e+03]
 [3.23e+03 1.64e+03]
 [3.66e+03 2.57e+03]
 [2.52e+04 1.45e+04]
 [2.60e+04 1.66e+04]
 [1.29e+04 1.35e+04]
 [3.47e+03 2.72e+03]
 [4.82e+03 1.82e+04]
 [9.35e+03 8.62e+03]
 [1.26e+04 9.72e+03]
 [2.38e+04 1.43e+04]
 [3.11e+04 2.15e+04]
 [1.01e+04 5.97e+03]
 [2.44e+04 1.47e+04]
 [3.18e+03 2.13e+03]
 [1.13e+04 5.44e+03]
 [7.30e+03 3.94e+03]
 [8.32e+03 8.53e+03]
 [4.04e+01 1.19e+04]
 [7.91e+03 6.84e+03]
 [3.59e+04 4.30e+04]
 [6.37e+03 3.93e+03]
 [6.45e+03 1.89e+04]
 [5.25e+02 2.12e+03]
 [1.05e+04 8.28e+03]
 [6.48e+03 3.37e+03]
 [9.48e+03 1.18e+04]
 [3.90e+04 4.79e+04]
 [2.80e+04 1.74e+04]
 [1.16e+04 9.29e+03]
 [3.54e+04 4.26e+04]
 [1.50e+04 1.32e+04]
 [7.12e+03 4.43e+03]
 [1.06e+04 9.38e+03]
 [7.05e+03 3.60e+03]
 [3.69e+04 2.91e+04]]

In [140]:
from sklearn.metrics import r2_score,mean_squared_error

print(r2_score(y_test, y_pred))
print(np.sqrt(mean_squared_error(y_test, y_pred)))

0.7958786376014414
5668.8400259119835

***Polynomial Regression***

In [116]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_train_poly = poly_reg.fit_transform(X_train)
X_test_poly = poly_reg.fit_transform(X_test)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_train_poly, y_train)

LinearRegression()

In [128]:
y_pred_poly=lin_reg_2.predict(X_test_poly)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_poly.reshape(len(y_pred_poly),1), y_test.reshape(len(y_test),1)),1))

[[ 1.15e+04  9.72e+03]
 [ 9.43e+03  8.55e+03]
 [ 6.76e+04  4.57e+04]
 [ 9.15e+03  1.30e+04]
 [ 1.66e+04  9.64e+03]
 [ 3.71e+03  4.50e+03]
 [ 3.01e+03  2.20e+03]
 [ 1.26e+04  1.14e+04]
 [ 8.62e+03  7.54e+03]
 [ 9.25e+03  5.43e+03]
 [ 6.19e+03  6.75e+03]
 [ 1.16e+04  1.05e+04]
 [ 8.46e+03  7.34e+03]
 [ 1.00e+04  4.19e+03]
 [ 2.00e+04  1.83e+04]
 [ 1.45e+04  1.07e+04]
 [ 1.33e+04  1.25e+04]
 [ 8.69e+03  3.49e+03]
 [ 8.12e+03  6.46e+03]
 [ 2.80e+04  3.35e+04]
 [ 2.34e+04  2.40e+04]
 [ 1.63e+04  1.26e+04]
 [ 1.14e+04  2.30e+04]
 [ 3.02e+04  2.31e+04]
 [ 3.34e+03  1.67e+03]
 [ 1.01e+04  4.67e+03]
 [ 7.84e+03  3.73e+03]
 [ 1.08e+04  7.68e+03]
 [ 8.25e+03  3.76e+03]
 [ 1.08e+04  8.41e+03]
 [ 8.20e+03  8.06e+03]
 [ 4.75e+04  4.90e+04]
 [ 1.32e+04  1.30e+04]
 [ 1.13e+04  2.06e+04]
 [ 1.18e+04  1.46e+04]
 [ 5.12e+03  4.14e+03]
 [ 9.26e+03  8.35e+03]
 [ 3.99e+04  5.12e+04]
 [ 4.16e+04  4.00e+04]
 [ 3.49e+03  1.88e+03]
 [ 7.80e+03  5.46e+03]
 [ 3.47e+03  2.87e+03]
 [ 2.80e+04  2.01e+04]
 [ 5.94e+04  4.75e+04]
 [ 3.38e+04  3.61e+04]
 [ 8.45e+03  2.60e+04]
 [ 1.42e+04  1.97e+04]
 [ 7.91e+03  6.94e+03]
 [ 7.15e+03  4.72e+03]
 [ 1.41e+04  2.22e+04]
 [ 5.98e+03  2.90e+03]
 [ 1.10e+04  1.88e+04]
 [ 2.88e+04  2.36e+04]
 [ 4.18e+04  4.63e+04]
 [ 1.21e+04  2.42e+04]
 [ 6.60e+03  3.27e+03]
 [ 3.58e+03  2.32e+03]
 [ 1.17e+04  8.83e+03]
 [ 1.69e+04  1.45e+04]
 [ 1.64e+04  1.31e+04]
 [ 2.70e+03  1.25e+03]
 [ 4.79e+04  4.67e+04]
 [ 1.70e+04  1.39e+04]
 [ 1.08e+04  9.63e+03]
 [ 1.52e+04  1.07e+04]
 [ 9.93e+03  9.88e+03]
 [ 2.11e+04  3.25e+04]
 [ 3.98e+04  3.87e+04]
 [-1.20e+04  3.18e+03]
 [ 9.62e+03  8.16e+03]
 [ 1.48e+04  1.30e+04]
 [ 1.32e+04  1.16e+04]
 [ 1.82e+04  1.62e+04]
 [ 1.49e+04  1.39e+04]
 [ 1.33e+04  1.30e+04]
 [ 1.42e+04  1.32e+04]
 [ 9.16e+03  7.15e+03]
 [ 1.08e+04  7.73e+03]
 [ 2.30e+04  2.03e+04]
 [ 5.00e+04  4.74e+04]
 [ 1.28e+04  1.17e+04]
 [ 6.23e+04  4.59e+04]
 [ 3.88e+03  2.06e+03]
 [ 8.32e+03  7.44e+03]
 [ 4.08e+04  4.10e+04]
 [ 2.04e+04  1.90e+04]
 [-2.23e+03  3.41e+03]
 [ 4.83e+03  2.70e+03]
 [ 1.51e+04  1.23e+04]
 [ 4.24e+04  3.68e+04]
 [ 1.37e+04  6.33e+03]
 [ 1.34e+04  1.02e+04]
 [ 2.44e+03  1.79e+04]
 [ 8.43e+03  8.52e+03]
 [ 6.87e+03  4.52e+03]
 [ 1.05e+04  5.15e+03]
 [ 3.64e+04  4.23e+04]
 [ 3.09e+04  3.90e+04]
 [ 8.11e+03  5.33e+03]
 [ 1.02e+04  1.06e+04]
 [ 3.26e+03  1.82e+03]
 [ 6.93e+03  5.38e+03]
 [ 4.82e+03  4.35e+03]
 [ 3.88e+04  3.77e+04]
 [ 2.61e+04  3.28e+04]
 [ 4.19e+03  3.35e+03]
 [ 9.43e+03  1.06e+04]
 [ 4.37e+03  3.56e+03]
 [ 1.31e+04  1.19e+04]
 [ 4.35e+04  5.26e+04]
 [ 1.20e+04  1.25e+04]
 [ 6.55e+03  4.27e+03]
 [ 1.00e+04  9.25e+03]
 [ 2.96e+04  3.37e+04]
 [ 4.77e+04  4.87e+04]
 [ 7.87e+03  7.73e+03]
 [ 2.11e+03  1.96e+03]
 [ 1.16e+04  8.44e+03]
 [ 1.47e+04  1.23e+04]
 [ 1.04e+04  9.30e+03]
 [ 4.49e+04  4.21e+04]
 [ 1.64e+04  9.99e+03]
 [ 1.37e+04  1.43e+04]
 [ 1.33e+04  5.43e+03]
 [ 9.19e+03  7.63e+03]
 [ 5.69e+03  4.91e+03]
 [ 2.69e+04  2.34e+04]
 [ 1.67e+04  2.11e+04]
 [ 4.94e+04  4.82e+04]
 [ 1.82e+03  1.92e+03]
 [ 8.71e+03  8.22e+03]
 [ 8.69e+03  1.73e+03]
 [ 6.00e+03  5.98e+03]
 [ 9.98e+03  9.36e+03]
 [ 3.63e+04  2.21e+04]
 [ 3.45e+04  3.55e+04]
 [ 2.91e+04  1.95e+04]
 [ 8.70e+03  1.01e+04]
 [ 2.24e+04  2.32e+04]
 [ 5.40e+03  2.79e+03]
 [ 9.99e+02  2.26e+03]
 [ 1.29e+04  1.06e+04]
 [ 1.02e+04  9.30e+03]
 [ 1.23e+04  1.04e+04]
 [ 5.50e+03  4.89e+03]
 [ 1.57e+04  1.43e+04]
 [ 1.37e+04  2.83e+04]
 [ 6.52e+03  1.44e+04]
 [ 3.18e+03  1.63e+03]
 [ 1.23e+04  2.55e+04]
 [ 9.17e+03  6.56e+03]
 [ 4.32e+04  3.96e+04]
 [ 1.34e+04  9.96e+03]
 [ 7.20e+03  1.72e+03]
 [ 1.33e+03  2.73e+03]
 [ 6.64e+03  6.50e+03]
 [ 5.75e+03  2.64e+03]
 [ 6.81e+03  1.72e+03]
 [ 1.05e+04  1.11e+04]
 [ 1.09e+04  1.01e+04]
 [ 1.06e+04  4.85e+03]
 [ 1.25e+04  1.30e+04]
 [ 1.26e+04  2.89e+04]
 [ 1.02e+04  9.39e+03]
 [ 5.93e+03  4.54e+03]
 [ 9.36e+03  1.71e+04]
 [ 1.55e+04  1.38e+04]
 [ 1.59e+04  6.11e+03]
 [ 5.17e+03  4.44e+03]
 [ 1.96e+03  1.63e+03]
 [ 8.37e+03  4.06e+03]
 [ 6.75e+03  4.44e+03]
 [ 9.39e+03  8.31e+03]
 [ 3.46e+03  1.99e+03]
 [ 5.28e+03  4.26e+03]
 [ 5.99e+01  4.50e+03]
 [ 4.75e+03  4.43e+03]
 [ 6.76e+03  6.12e+03]
 [ 4.10e+04  3.02e+04]
 [ 2.41e+03  1.71e+03]
 [ 1.34e+04  1.12e+04]
 [ 9.38e+03  6.80e+03]
 [ 1.15e+04  1.14e+04]
 [ 3.66e+03  2.50e+03]
 [ 5.07e+03  2.74e+04]
 [ 2.81e+04  2.81e+04]
 [ 5.71e+03  2.25e+03]
 [ 4.65e+03  2.60e+03]
 [ 1.37e+04  1.47e+04]
 [ 1.48e+04  1.04e+04]
 [ 3.84e+04  4.11e+04]
 [ 2.40e+03  3.98e+03]
 [ 7.06e+03  5.47e+03]
 [ 3.14e+04  2.12e+04]
 [ 3.74e+03  2.53e+03]
 [ 4.05e+03  1.97e+03]
 [ 8.81e+03  6.41e+03]
 [ 1.46e+04  6.55e+03]
 [ 8.41e+03  4.06e+03]
 [ 5.51e+03  4.24e+03]
 [ 1.52e+04  1.15e+04]
 [ 4.75e+04  4.69e+04]
 [ 1.54e+04  1.23e+04]
 [ 1.72e+04  1.92e+04]
 [ 8.02e+03  4.43e+03]
 [ 4.19e+04  4.30e+04]
 [ 6.00e+03  2.32e+04]
 [ 1.15e+04  9.14e+03]
 [ 6.57e+03  5.84e+03]
 [ 2.21e+03  1.15e+03]
 [ 1.08e+04  8.77e+03]
 [ 1.56e+04  1.40e+04]
 [ 7.61e+03  5.31e+03]
 [ 4.12e+03  1.08e+04]
 [ 7.00e+03  6.28e+03]
 [ 3.43e+03  1.97e+03]
 [ 7.19e+03  6.75e+03]
 [ 7.37e+03  5.35e+03]
 [ 2.06e+04  1.40e+04]
 [ 8.00e+03  6.88e+03]
 [ 2.44e+03  6.20e+03]
 [ 9.22e+03  7.99e+03]
 [ 8.65e+03  8.28e+03]
 [ 3.19e+03  3.21e+03]
 [ 1.19e+04  1.18e+04]
 [ 8.74e+03  1.42e+04]
 [ 1.34e+04  1.23e+04]
 [ 1.31e+04  1.18e+04]
 [ 4.17e+03  6.65e+03]
 [ 2.15e+03  2.14e+03]
 [ 2.62e+03  1.13e+03]
 [ 1.36e+04  8.34e+03]
 [ 1.34e+04  1.22e+04]
 [ 2.12e+04  4.56e+03]
 [ 3.71e+03  1.76e+04]
 [ 6.95e+03  6.88e+03]
 [ 1.13e+04  9.45e+03]
 [ 3.02e+04  3.43e+04]
 [ 6.70e+03  6.07e+03]
 [ 1.07e+04  1.17e+04]
 [ 6.67e+03  5.38e+03]
 [ 4.41e+04  3.75e+04]
 [ 6.05e+03  7.37e+03]
 [ 7.84e+03  7.33e+03]
 [ 1.04e+04  8.41e+03]
 [ 1.31e+04  1.05e+04]
 [ 7.48e+03  3.28e+03]
 [ 9.98e+03  7.73e+03]
 [ 2.46e+03  2.73e+03]
 [ 6.18e+03  6.86e+03]
 [ 2.33e+04  1.95e+04]
 [ 4.51e+04  4.73e+04]
 [ 4.41e+03  3.99e+03]
 [ 2.93e+03  3.24e+03]
 [ 4.51e+03  7.32e+03]
 [ 4.86e+02  1.70e+03]
 [ 7.98e+03  7.45e+03]
 [ 2.80e+03  1.63e+03]
 [ 6.78e+03  4.88e+03]
 [ 1.92e+03  3.56e+03]
 [ 9.40e+03  8.61e+03]
 [ 3.09e+04  2.45e+04]
 [ 3.32e+04  4.57e+04]
 [ 1.97e+04  1.50e+04]
 [ 7.74e+03  6.66e+03]
 [ 9.82e+03  2.07e+04]
 [ 4.18e+04  4.09e+04]
 [ 8.60e+03  9.50e+03]
 [ 3.46e+04  4.02e+04]
 [ 3.48e+03  1.14e+03]
 [ 4.39e+04  3.85e+04]
 [ 4.65e+03  4.67e+03]
 [ 1.70e+04  1.30e+04]
 [ 7.38e+03  4.19e+03]
 [ 3.89e+04  3.87e+04]
 [ 1.08e+04  5.59e+03]
 [ 1.23e+04  2.73e+04]
 [ 2.00e+04  9.79e+03]
 [ 5.79e+03  2.36e+03]
 [ 1.94e+04  1.32e+04]
 [ 1.16e+04  1.22e+04]
 [ 6.24e+03  4.32e+03]
 [ 1.46e+04  1.27e+04]
 [ 4.93e+03  2.20e+03]
 [ 1.08e+04  6.08e+03]
 [ 4.50e+03  3.59e+03]
 [ 3.20e+04  8.60e+03]
 [ 2.41e+04  2.18e+04]
 [ 5.91e+03  2.93e+03]
 [ 1.94e+03  1.71e+03]
 [ 6.86e+03  2.80e+03]
 [ 4.65e+04  4.85e+04]
 [ 9.93e+03  9.28e+03]
 [ 6.16e+03  4.74e+03]
 [ 1.56e+04  1.23e+04]
 [ 1.57e+04  1.19e+04]
 [ 2.93e+04  3.42e+04]
 [ 7.91e+03  6.50e+03]
 [ 5.34e+03  4.75e+03]
 [ 1.04e+04  8.46e+03]
 [ 3.51e+03  1.64e+03]
 [ 8.38e+03  2.57e+03]
 [ 1.89e+04  1.45e+04]
 [ 2.19e+04  1.66e+04]
 [ 1.73e+04  1.35e+04]
 [ 2.56e+03  2.72e+03]
 [ 4.48e+03  1.82e+04]
 [ 9.02e+03  8.62e+03]
 [ 1.15e+04  9.72e+03]
 [ 8.38e+03  1.43e+04]
 [ 2.34e+04  2.15e+04]
 [ 1.00e+03  5.97e+03]
 [ 1.66e+04  1.47e+04]
 [ 4.74e+02  2.13e+03]
 [ 5.78e+03  5.44e+03]
 [ 4.90e+03  3.94e+03]
 [ 9.29e+03  8.53e+03]
 [-2.17e+03  1.19e+04]
 [ 7.13e+03  6.84e+03]
 [ 7.94e+04  4.30e+04]
 [ 1.37e+04  3.93e+03]
 [ 1.08e+04  1.89e+04]
 [ 8.45e+02  2.12e+03]
 [ 9.03e+03  8.28e+03]
 [ 3.51e+03  3.37e+03]
 [ 1.83e+04  1.18e+04]
 [ 4.98e+04  4.79e+04]
 [ 1.21e+04  1.74e+04]
 [ 1.21e+04  9.29e+03]
 [ 4.57e+04  4.26e+04]
 [ 1.72e+04  1.32e+04]
 [ 8.10e+03  4.43e+03]
 [ 1.15e+04  9.38e+03]
 [ 2.90e+03  3.60e+03]
 [ 3.50e+04  2.91e+04]]

In [139]:
print(r2_score(y_test, y_pred_poly))
print(np.sqrt(mean_squared_error(y_test, y_pred_poly)))

0.7939681652666519
5695.306973342998

**SVR**

In [122]:
from sklearn.svm import SVR
regressor_SVR = SVR(kernel = 'rbf')
regressor_SVR.fit(X_train, y_train)

SVR()

In [123]:
y_pred_SVR=regressor_SVR.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_SVR.reshape(len(y_pred_SVR),1), y_test.reshape(len(y_test),1)),1))

[[ 9497.97  9724.53]
 [ 9470.8   8547.69]
 [ 9479.71 45702.02]
 [ 9537.72 12950.07]
 [ 9484.95  9644.25]
 [ 9397.29  4500.34]
 [ 9338.81  2198.19]
 [ 9494.58 11436.74]
 [ 9420.49  7537.16]
 [ 9384.81  5425.02]
 [ 9397.53  6753.04]
 [ 9485.56 10493.95]
 [ 9448.43  7337.75]
 [ 9392.45  4185.1 ]
 [ 9366.51 18310.74]
 [ 9486.57 10702.64]
 [ 9529.98 12523.6 ]
 [ 9363.99  3490.55]
 [ 9420.1   6457.84]
 [ 9344.32 33475.82]
 [ 9490.1  23967.38]
 [ 9518.26 12643.38]
 [ 9498.21 23045.57]
 [ 9470.22 23065.42]
 [ 9351.24  1674.63]
 [ 9393.23  4667.61]
 [ 9371.92  3732.63]
 [ 9432.87  7682.67]
 [ 9383.06  3756.62]
 [ 9460.12  8413.46]
 [ 9431.    8059.68]
 [ 9529.75 48970.25]
 [ 9541.27 12979.36]
 [ 9513.99 20630.28]
 [ 9356.37 14571.89]
 [ 9378.88  4137.52]
 [ 9468.43  8347.16]
 [ 9374.81 51194.56]
 [ 9432.9  40003.33]
 [ 9345.4   1880.49]
 [ 9407.24  5458.05]
 [ 9374.51  2867.12]
 [ 9424.71 20149.32]
 [ 9527.01 47496.49]
 [ 9343.87 36149.48]
 [ 9347.71 26018.95]
 [ 9486.4  19749.38]
 [ 9441.31  6940.91]
 [ 9378.56  4718.2 ]
 [ 9517.76 22192.44]
 [ 9355.    2899.49]
 [ 9341.19 18838.7 ]
 [ 9475.87 23568.27]
 [ 9494.82 46255.11]
 [ 9525.47 24227.34]
 [ 9373.87  3268.85]
 [ 9365.93  2322.62]
 [ 9485.66  8827.21]
 [ 9446.71 14478.33]
 [ 9530.02 13112.6 ]
 [ 9341.17  1253.94]
 [ 9541.   46718.16]
 [ 9534.45 13919.82]
 [ 9488.37  9630.4 ]
 [ 9478.63 10736.87]
 [ 9494.83  9880.07]
 [ 9341.79 32548.34]
 [ 9386.8  38746.36]
 [ 9346.92  3180.51]
 [ 9432.01  8162.72]
 [ 9536.31 13041.92]
 [ 9520.51 11554.22]
 [ 9343.56 16232.85]
 [ 9544.49 13887.97]
 [ 9529.72 13012.21]
 [ 9532.33 13217.09]
 [ 9461.76  7147.1 ]
 [ 9454.53  7731.43]
 [ 9413.5  20296.86]
 [ 9538.28 47403.88]
 [ 9516.52 11658.38]
 [ 9454.65 45863.21]
 [ 9350.25  2055.32]
 [ 9459.96  7441.05]
 [ 9450.8  41034.22]
 [ 9397.87 18972.49]
 [ 9372.73  3410.32]
 [ 9363.3   2699.57]
 [ 9528.49 12333.83]
 [ 9382.65 36837.47]
 [ 9393.16  6334.34]
 [ 9512.45 10214.64]
 [ 9367.93 17878.9 ]
 [ 9458.9   8515.76]
 [ 9401.32  4518.83]
 [ 9389.61  5148.55]
 [ 9512.93 42303.69]
 [ 9454.48 38998.55]
 [ 9385.51  5327.4 ]
 [ 9517.96 10602.39]
 [ 9353.56  1824.29]
 [ 9411.29  5377.46]
 [ 9372.28  4349.46]
 [ 9411.8  37742.58]
 [ 9442.36 32787.46]
 [ 9366.36  3353.47]
 [ 9511.82 10577.09]
 [ 9373.35  3556.92]
 [ 9526.93 11944.59]
 [ 9534.53 52590.83]
 [ 9502.2  12475.35]
 [ 9390.61  4266.17]
 [ 9476.11  9249.5 ]
 [ 9340.22 33732.69]
 [ 9521.62 48675.52]
 [ 9441.26  7729.65]
 [ 9344.37  1964.78]
 [ 9485.75  8444.47]
 [ 9530.81 12347.17]
 [ 9463.57  9301.89]
 [ 9451.24 42124.52]
 [ 9490.03  9991.04]
 [ 9546.33 14319.03]
 [ 9384.19  5428.73]
 [ 9453.07  7626.99]
 [ 9374.74  4906.41]
 [ 9469.42 23401.31]
 [ 9456.79 21098.55]
 [ 9533.82 48173.36]
 [ 9350.88  1917.32]
 [ 9454.11  8219.2 ]
 [ 9341.21  1725.55]
 [ 9420.6   5976.83]
 [ 9488.34  9361.33]
 [ 9442.98 22144.03]
 [ 9399.51 35491.64]
 [ 9440.8  19515.54]
 [ 9483.94 10107.22]
 [ 9498.74 23244.79]
 [ 9351.81  2789.06]
 [ 9344.63  2261.57]
 [ 9511.34 10594.5 ]
 [ 9484.42  9304.7 ]
 [ 9508.78 10435.07]
 [ 9397.63  4894.75]
 [ 9547.55 14313.85]
 [ 9530.87 28287.9 ]
 [ 9352.13 14426.07]
 [ 9342.25  1627.28]
 [ 9505.32 25517.11]
 [ 9419.27  6555.07]
 [ 9376.38 39611.76]
 [ 9493.65  9964.06]
 [ 9339.36  1720.35]
 [ 9348.77  2730.11]
 [ 9431.39  6500.24]
 [ 9349.87  2643.27]
 [ 9339.17  1719.44]
 [ 9486.55 11085.59]
 [ 9472.61 10115.01]
 [ 9368.1   4846.92]
 [ 9540.4  12982.87]
 [ 9531.16 28923.14]
 [ 9494.86  9391.35]
 [ 9387.76  4544.23]
 [ 9357.82 17128.43]
 [ 9342.4  13844.51]
 [ 9384.49  6113.23]
 [ 9383.3   4441.21]
 [ 9346.89  1633.96]
 [ 9368.34  4058.71]
 [ 9370.11  4435.09]
 [ 9448.8   8310.84]
 [ 9359.12  1986.93]
 [ 9367.03  4260.74]
 [ 9361.34  4504.66]
 [ 9370.15  4428.89]
 [ 9423.26  6117.49]
 [ 9529.77 30184.94]
 [ 9338.88  1708.93]
 [ 9498.55 11187.66]
 [ 9415.35  6796.86]
 [ 9522.64 11356.66]
 [ 9368.59  2498.41]
 [ 9397.35 27375.9 ]
 [ 9538.93 28101.33]
 [ 9350.04  2254.8 ]
 [ 9345.85  2597.78]
 [ 9547.6  14692.67]
 [ 9483.37 10370.91]
 [ 9488.33 41097.16]
 [ 9362.84  3981.98]
 [ 9408.06  5472.45]
 [ 9473.97 21223.68]
 [ 9362.41  2534.39]
 [ 9354.96  1972.95]
 [ 9414.85  6406.41]
 [ 9397.4   6551.75]
 [ 9379.62  4058.12]
 [ 9383.74  4243.59]
 [ 9508.65 11512.41]
 [ 9547.77 46889.26]
 [ 9513.48 12268.63]
 [ 9383.47 19199.94]
 [ 9375.94  4433.39]
 [ 9473.58 42969.85]
 [ 9358.47 23241.47]
 [ 9499.24  9140.95]
 [ 9407.19  5836.52]
 [ 9351.17  1149.4 ]
 [ 9477.58  8765.25]
 [ 9541.22 14043.48]
 [ 9370.08  5312.17]
 [ 9353.99 10795.94]
 [ 9436.65  6282.23]
 [ 9355.24  1969.61]
 [ 9408.69  6746.74]
 [ 9392.36  5354.07]
 [ 9528.6  14001.29]
 [ 9412.36  6877.98]
 [ 9403.56  6196.45]
 [ 9423.63  7986.48]
 [ 9476.08  8277.52]
 [ 9358.55  3206.49]
 [ 9526.64 11848.14]
 [ 9547.1  14210.54]
 [ 9518.45 12265.51]
 [ 9522.84 11837.16]
 [ 9417.86  6652.53]
 [ 9358.41  2137.65]
 [ 9339.4   1131.51]
 [ 9468.74  8342.91]
 [ 9530.87 12244.53]
 [ 9340.17  4561.19]
 [ 9387.6  17626.24]
 [ 9438.13  6875.96]
 [ 9475.39  9447.38]
 [ 9356.29 34254.05]
 [ 9419.59  6067.13]
 [ 9499.27 11729.68]
 [ 9419.36  5383.54]
 [ 9347.56 37465.34]
 [ 9440.31  7371.77]
 [ 9446.38  7325.05]
 [ 9448.63  8410.05]
 [ 9503.39 10461.98]
 [ 9345.99  3279.87]
 [ 9450.42  7727.25]
 [ 9349.11  2731.91]
 [ 9434.82  6858.48]
 [ 9379.21 19521.97]
 [ 9544.61 47305.31]
 [ 9365.03  3987.93]
 [ 9368.9   3238.44]
 [ 9339.05  7323.73]
 [ 9339.63  1704.57]
 [ 9461.38  7445.92]
 [ 9343.67  1629.83]
 [ 9358.79  4877.98]
 [ 9365.98  3561.89]
 [ 9455.41  8605.36]
 [ 9486.43 24520.26]
 [ 9541.4  45710.21]
 [ 9540.84 15019.76]
 [ 9436.5   6664.69]
 [ 9522.17 20709.02]
 [ 9385.7  40932.43]
 [ 9463.11  9500.57]
 [ 9417.15 40182.25]
 [ 9341.68  1137.47]
 [ 9356.74 38511.63]
 [ 9391.77  4670.64]
 [ 9526.56 13019.16]
 [ 9358.45  4189.11]
 [ 9412.24 38709.18]
 [ 9400.47  5594.85]
 [ 9503.43 27346.04]
 [ 9457.32  9788.87]
 [ 9344.93  2362.23]
 [ 9532.98 13224.69]
 [ 9524.21 12222.9 ]
 [ 9402.03  4320.41]
 [ 9533.45 12731.  ]
 [ 9339.31  2203.47]
 [ 9423.84  6079.67]
 [ 9353.8   3591.48]
 [ 9428.04  8596.83]
 [ 9446.65 21771.34]
 [ 9378.1   2927.06]
 [ 9338.96  1708.  ]
 [ 9342.92  2803.7 ]
 [ 9538.29 48517.56]
 [ 9480.05  9282.48]
 [ 9385.41  4738.27]
 [ 9513.66 12269.69]
 [ 9513.4  11879.1 ]
 [ 9353.1  34166.27]
 [ 9430.42  6496.89]
 [ 9404.38  4751.07]
 [ 9489.38  8457.82]
 [ 9341.71  1639.56]
 [ 9344.37  2566.47]
 [ 9364.93 14455.64]
 [ 9366.04 16577.78]
 [ 9540.58 13457.96]
 [ 9358.41  2721.32]
 [ 9360.1  18218.16]
 [ 9458.79  8615.3 ]
 [ 9499.04  9722.77]
 [ 9340.37 14283.46]
 [ 9388.82 21472.48]
 [ 9399.3   5972.38]
 [ 9344.36 14711.74]
 [ 9341.62  2128.43]
 [ 9437.1   5438.75]
 [ 9401.05  3935.18]
 [ 9468.29  8534.67]
 [ 9340.25 11884.05]
 [ 9446.82  6837.37]
 [ 9457.78 42983.46]
 [ 9351.78  3925.76]
 [ 9367.78 18903.49]
 [ 9341.84  2117.34]
 [ 9477.87  8283.68]
 [ 9378.14  3366.67]
 [ 9520.84 11833.78]
 [ 9547.79 47928.03]
 [ 9378.76 17361.77]
 [ 9482.68  9290.14]
 [ 9452.04 42560.43]
 [ 9522.71 13224.06]
 [ 9376.14  4433.92]
 [ 9492.76  9377.9 ]
 [ 9357.11  3597.6 ]
 [ 9536.87 29141.36]]

In [138]:
print(r2_score(y_test, y_pred_SVR))
print(np.sqrt(mean_squared_error(y_test, y_pred_SVR)))

-0.09775588810693181
13146.279451129414

**Desicion Tree**

In [125]:
from sklearn.tree import DecisionTreeRegressor
regressor_DT = DecisionTreeRegressor(random_state = 0)
regressor_DT.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [126]:
y_pred_DT=regressor_DT.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_DT.reshape(len(y_pred_DT),1), y_test.reshape(len(y_test),1)),1))

[[ 9748.91  9724.53]
 [ 8233.1   8547.69]
 [44202.65 45702.02]
 [12741.17 12950.07]
 [ 9855.13  9644.25]
 [21984.47  4500.34]
 [ 2200.83  2198.19]
 [10600.55 11436.74]
 [ 7281.51  7537.16]
 [ 6128.8   5425.02]
 [ 4766.02  6753.04]
 [30284.64 10493.95]
 [ 6849.03  7337.75]
 [ 4779.6   4185.1 ]
 [35147.53 18310.74]
 [ 8233.1  10702.64]
 [12323.94 12523.6 ]
 [ 3292.53  3490.55]
 [ 6455.86  6457.84]
 [33907.55 33475.82]
 [24667.42 23967.38]
 [12495.29 12643.38]
 [ 9625.92 23045.57]
 [24915.22 23065.42]
 [ 1391.53  1674.63]
 [ 4462.72  4667.61]
 [ 3558.62  3732.63]
 [ 6185.32  7682.67]
 [ 3736.46  3756.62]
 [ 7731.86  8413.46]
 [ 7201.7   8059.68]
 [48673.56 48970.25]
 [13462.52 12979.36]
 [ 9850.43 20630.28]
 [15359.1  14571.89]
 [ 3866.86  4137.52]
 [ 8978.19  8347.16]
 [36219.41 51194.56]
 [39983.43 40003.33]
 [ 1391.53  1880.49]
 [21984.47  5458.05]
 [ 3972.92  2867.12]
 [21082.16 20149.32]
 [49577.66 47496.49]
 [37133.9  36149.48]
 [ 3579.83 26018.95]
 [ 8232.64 19749.38]
 [ 6358.78  6940.91]
 [ 4719.52  4718.2 ]
 [27117.99 22192.44]
 [ 2473.33  2899.49]
 [22493.66 18838.7 ]
 [25309.49 23568.27]
 [46661.44 46255.11]
 [11856.41 24227.34]
 [19673.34  3268.85]
 [ 3292.53  2322.62]
 [30284.64  8827.21]
 [ 8606.22 14478.33]
 [12913.99 13112.6 ]
 [ 1252.41  1253.94]
 [47291.06 46718.16]
 [14001.13 13919.82]
 [10118.42  9630.4 ]
 [26392.26 10736.87]
 [ 9875.68  9880.07]
 [33907.55 32548.34]
 [39983.43 38746.36]
 [ 3077.1   3180.51]
 [ 9222.4   8162.72]
 [13451.12 13041.92]
 [12224.35 11554.22]
 [19040.88 16232.85]
 [13887.2  13887.97]
 [12629.9  13012.21]
 [12233.83 13217.09]
 [ 7526.71  7147.1 ]
 [17929.3   7731.43]
 [19539.24 20296.86]
 [47896.79 47403.88]
 [11658.12 11658.38]
 [43896.38 45863.21]
 [ 1909.53  2055.32]
 [ 6849.03  7441.05]
 [42211.14 41034.22]
 [20984.09 18972.49]
 [ 2904.09  3410.32]
 [ 2727.4   2699.57]
 [12913.99 12333.83]
 [44585.46 36837.47]
 [ 4837.58  6334.34]
 [ 9850.43 10214.64]
 [ 3021.81 17878.9 ]
 [ 8516.83  8515.76]
 [12404.88  4518.83]
 [ 4462.72  5148.55]
 [41999.52 42303.69]
 [43943.88 38998.55]
 [ 4934.7   5327.4 ]
 [10601.41 10602.39]
 [ 1981.58  1824.29]
 [ 5630.46  5377.46]
 [ 4449.46  4349.46]
 [37270.15 37742.58]
 [37829.72 32787.46]
 [ 3558.62  3353.47]
 [11345.52 10577.09]
 [19673.34  3556.92]
 [11743.93 11944.59]
 [45008.96 52590.83]
 [12479.71 12475.35]
 [ 4753.64  4266.17]
 [ 8930.93  9249.5 ]
 [34672.15 33732.69]
 [47269.85 48675.52]
 [13725.47  7729.65]
 [ 1832.09  1964.78]
 [ 9861.02  8444.47]
 [27941.29 12347.17]
 [30284.64  9301.89]
 [42211.14 42124.52]
 [10355.64  9991.04]
 [14901.52 14319.03]
 [ 4837.58  5428.73]
 [ 7624.63  7626.99]
 [ 4719.74  4906.41]
 [38245.59 23401.31]
 [35069.37 21098.55]
 [48673.56 48173.36]
 [ 1646.43  1917.32]
 [17929.3   8219.2 ]
 [ 1727.54  1725.55]
 [ 6313.76  5976.83]
 [ 8688.86  9361.33]
 [62592.87 22144.03]
 [37079.37 35491.64]
 [21259.38 19515.54]
 [10156.78 10107.22]
 [22218.11 23244.79]
 [12609.89  2789.06]
 [ 2459.72  2261.57]
 [10796.35 10594.5 ]
 [ 8978.19  9304.7 ]
 [10923.93 10435.07]
 [ 5385.34  4894.75]
 [14901.52 14313.85]
 [14474.67 28287.9 ]
 [ 3077.1  14426.07]
 [ 1628.47  1627.28]
 [10942.13 25517.11]
 [ 7077.19  6555.07]
 [38126.25 39611.76]
 [ 9866.3   9964.06]
 [21344.85  1720.35]
 [ 2219.45  2730.11]
 [ 5974.38  6500.24]
 [ 2719.28  2643.27]
 [ 1711.03  1719.44]
 [11015.17 11085.59]
 [ 9583.89 10115.01]
 [ 4922.92  4846.92]
 [13470.8  12982.87]
 [12815.44 28923.14]
 [ 9048.03  9391.35]
 [ 4134.08  4544.23]
 [ 3443.06 17128.43]
 [13747.87 13844.51]
 [ 4837.58  6113.23]
 [ 4237.13  4441.21]
 [ 1634.57  1633.96]
 [ 4922.92  4058.71]
 [ 3847.67  4435.09]
 [19144.58  8310.84]
 [ 1837.28  1986.93]
 [18804.75  4260.74]
 [ 3443.06  4504.66]
 [ 3847.67  4428.89]
 [ 6123.57  6117.49]
 [27218.44 30184.94]
 [ 1705.62  1708.93]
 [12495.29 11187.66]
 [ 6203.9   6796.86]
 [10976.25 11356.66]
 [19673.34  2498.41]
 [ 4766.02 27375.9 ]
 [26109.33 28101.33]
 [ 1909.53  2254.8 ]
 [ 2585.27  2597.78]
 [14901.52 14692.67]
 [ 8334.46 10370.91]
 [41919.1  41097.16]
 [ 2304.    3981.98]
 [ 5227.99  5472.45]
 [21978.68 21223.68]
 [ 3292.53  2534.39]
 [18955.22  1972.95]
 [ 6985.51  6406.41]
 [ 5989.52  6551.75]
 [ 3277.16  4058.12]
 [ 4527.18  4243.59]
 [10928.85 11512.41]
 [45008.96 46889.26]
 [12495.29 12268.63]
 [17904.53 19199.94]
 [ 4922.92  4433.39]
 [41676.08 42969.85]
 [ 4564.19 23241.47]
 [10564.88  9140.95]
 [ 4890.    5836.52]
 [ 1146.8   1149.4 ]
 [10269.46  8765.25]
 [13555.   14043.48]
 [ 4133.64  5312.17]
 [ 2473.33 10795.94]
 [ 6600.36  6282.23]
 [25081.77  1969.61]
 [ 6548.2   6746.74]
 [ 4766.02  5354.07]
 [14001.13 14001.29]
 [ 6985.51  6877.98]
 [ 5989.52  6196.45]
 [ 7985.81  7986.48]
 [ 8823.28  8277.52]
 [ 3176.82  3206.49]
 [11674.13 11848.14]
 [14410.93 14210.54]
 [12629.17 12265.51]
 [10959.33 11837.16]
 [ 6338.08  6652.53]
 [ 2302.3   2137.65]
 [21344.85  1131.51]
 [ 8978.19  8342.91]
 [21797.   12244.53]
 [ 4466.62  4561.19]
 [ 4032.24 17626.24]
 [ 6775.96  6875.96]
 [ 9447.25  9447.38]
 [34672.15 34254.05]
 [ 7077.19  6067.13]
 [12096.65 11729.68]
 [ 5488.26  5383.54]
 [35585.58 37465.34]
 [ 7650.77  7371.77]
 [ 7623.52  7325.05]
 [18806.15  8410.05]
 [10085.85 10461.98]
 [ 4564.19  3279.87]
 [ 7345.73  7727.25]
 [ 1515.34  2731.91]
 [13725.47  6858.48]
 [18033.97 19521.97]
 [45008.96 47305.31]
 [ 3579.83  3987.93]
 [ 3227.12  3238.44]
 [ 2200.83  7323.73]
 [ 1704.7   1704.57]
 [ 6849.03  7445.92]
 [ 2211.13  1629.83]
 [24671.66  4877.98]
 [23288.93  3561.89]
 [ 8891.14  8605.36]
 [24535.7  24520.26]
 [45008.96 45710.21]
 [15612.19 15019.76]
 [ 6393.6   6664.69]
 [11566.3  20709.02]
 [39241.44 40932.43]
 [ 9101.8   9500.57]
 [39047.29 40182.25]
 [ 1137.01  1137.47]
 [36219.41 38511.63]
 [ 5152.13  4670.64]
 [11946.63 13019.16]
 [ 3537.7   4189.11]
 [39774.28 38709.18]
 [ 5012.47  5594.85]
 [ 9487.64 27346.04]
 [ 8442.67  9788.87]
 [ 2719.28  2362.23]
 [12913.99 13224.69]
 [12224.35 12222.9 ]
 [12404.88  4320.41]
 [13143.34 12731.  ]
 [21344.85  2203.47]
 [ 6610.11  6079.67]
 [ 3443.06  3591.48]
 [ 8582.3   8596.83]
 [21259.38 21771.34]
 [ 3292.53  2927.06]
 [ 1705.62  1708.  ]
 [ 3077.1   2803.7 ]
 [47896.79 48517.56]
 [ 9861.02  9282.48]
 [ 4462.72  4738.27]
 [12495.29 12269.69]
 [10601.63 11879.1 ]
 [34439.86 34166.27]
 [ 6600.36  6496.89]
 [ 4746.34  4751.07]
 [ 9872.7   8457.82]
 [ 1639.56  1639.56]
 [ 3056.39  2566.47]
 [32734.19 14455.64]
 [17085.27 16577.78]
 [13352.1  13457.96]
 [ 2302.3   2721.32]
 [ 3227.12 18218.16]
 [ 9617.66  8615.3 ]
 [10564.88  9722.77]
 [13747.87 14283.46]
 [17560.38 21472.48]
 [ 4795.66  5972.38]
 [20167.34 14711.74]
 [ 2130.68  2128.43]
 [ 5662.23  5438.75]
 [12404.88  3935.18]
 [ 8932.08  8534.67]
 [ 3077.1  11884.05]
 [ 7726.85  6837.37]
 [48885.14 42983.46]
 [ 3579.83  3925.76]
 [ 4922.92 18903.49]
 [ 1607.51  2117.34]
 [ 8240.59  8283.68]
 [19673.34  3366.67]
 [27117.99 11833.78]
 [45008.96 47928.03]
 [18765.88 17361.77]
 [ 8964.06  9290.14]
 [41949.24 42560.43]
 [13430.26 13224.06]
 [ 4922.92  4433.92]
 [ 8280.62  9377.9 ]
 [ 3443.06  3597.6 ]
 [28868.66 29141.36]]

In [137]:
print(r2_score(y_test, y_pred_DT))
print(np.sqrt(mean_squared_error(y_test, y_pred_DT)))

0.7103358863330081
6753.008855917468

***Random Forest***

In [130]:
from sklearn.ensemble import RandomForestRegressor
regressor_RF = RandomForestRegressor(n_estimators = 150, random_state = 0)
regressor_RF.fit(X_train, y_train)

RandomForestRegressor(n_estimators=150, random_state=0)

In [131]:
y_pred_RF=regressor_RF.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_RF.reshape(len(y_pred_RF),1), y_test.reshape(len(y_test),1)),1))

[[10444.35  9724.53]
 [ 9663.66  8547.69]
 [45675.59 45702.02]
 [13192.89 12950.07]
 [ 9501.53  9644.25]
 [11134.24  4500.34]
 [ 2045.5   2198.19]
 [13486.39 11436.74]
 [ 7261.03  7537.16]
 [ 6881.51  5425.02]
 [ 7458.38  6753.04]
 [19079.41 10493.95]
 [ 9509.11  7337.75]
 [ 6957.89  4185.1 ]
 [25761.63 18310.74]
 [14616.85 10702.64]
 [13313.02 12523.6 ]
 [ 3878.74  3490.55]
 [ 6736.37  6457.84]
 [34033.74 33475.82]
 [24010.98 23967.38]
 [16476.94 12643.38]
 [10586.17 23045.57]
 [27173.88 23065.42]
 [ 2237.62  1674.63]
 [ 5630.78  4667.61]
 [ 6680.04  3732.63]
 [ 8934.39  7682.67]
 [ 3882.31  3756.62]
 [11421.78  8413.46]
 [ 7746.1   8059.68]
 [48365.07 48970.25]
 [14167.25 12979.36]
 [10891.75 20630.28]
 [16464.66 14571.89]
 [ 4558.14  4137.52]
 [ 9354.4   8347.16]
 [37806.89 51194.56]
 [40069.48 40003.33]
 [ 4946.37  1880.49]
 [ 9150.54  5458.05]
 [ 3992.71  2867.12]
 [20783.94 20149.32]
 [47555.2  47496.49]
 [37104.67 36149.48]
 [ 5840.9  26018.95]
 [14600.92 19749.38]
 [ 6728.97  6940.91]
 [ 4817.09  4718.2 ]
 [14898.99 22192.44]
 [ 3148.16  2899.49]
 [15812.65 18838.7 ]
 [27613.59 23568.27]
 [48639.17 46255.11]
 [11658.5  24227.34]
 [ 8448.26  3268.85]
 [ 3444.17  2322.62]
 [12012.5   8827.21]
 [10097.32 14478.33]
 [16593.57 13112.6 ]
 [ 1387.77  1253.94]
 [46654.28 46718.16]
 [15535.32 13919.82]
 [15113.9   9630.4 ]
 [13991.69 10736.87]
 [10358.32  9880.07]
 [33930.41 32548.34]
 [42636.15 38746.36]
 [ 4301.87  3180.51]
 [10914.79  8162.72]
 [16806.69 13041.92]
 [13143.97 11554.22]
 [18461.99 16232.85]
 [14146.47 13887.97]
 [13197.42 13012.21]
 [14605.92 13217.09]
 [11622.67  7147.1 ]
 [15274.92  7731.43]
 [19900.37 20296.86]
 [46695.48 47403.88]
 [11580.8  11658.38]
 [50099.54 45863.21]
 [ 2436.62  2055.32]
 [ 8699.11  7441.05]
 [40694.24 41034.22]
 [19360.3  18972.49]
 [ 4230.91  3410.32]
 [ 3722.23  2699.57]
 [17135.81 12333.83]
 [39089.19 36837.47]
 [ 6382.02  6334.34]
 [12130.97 10214.64]
 [ 3055.36 17878.9 ]
 [ 9608.68  8515.76]
 [ 8021.31  4518.83]
 [ 4598.17  5148.55]
 [42812.87 42303.69]
 [51310.5  38998.55]
 [ 6091.    5327.4 ]
 [10897.63 10602.39]
 [ 2851.05  1824.29]
 [ 6758.98  5377.46]
 [ 5510.18  4349.46]
 [38720.36 37742.58]
 [27249.55 32787.46]
 [ 3960.55  3353.47]
 [11166.89 10577.09]
 [10122.43  3556.92]
 [11607.14 11944.59]
 [45333.69 52590.83]
 [12568.84 12475.35]
 [ 6027.71  4266.17]
 [11062.85  9249.5 ]
 [34551.49 33732.69]
 [47833.86 48675.52]
 [ 7228.91  7729.65]
 [ 2081.02  1964.78]
 [11436.23  8444.47]
 [22658.93 12347.17]
 [10391.96  9301.89]
 [42026.76 42124.52]
 [11965.67  9991.04]
 [14339.73 14319.03]
 [ 7321.13  5428.73]
 [ 9077.5   7626.99]
 [ 5840.5   4906.41]
 [27272.3  23401.31]
 [27065.06 21098.55]
 [48568.06 48173.36]
 [ 1806.05  1917.32]
 [16936.27  8219.2 ]
 [ 4421.66  1725.55]
 [ 6242.52  5976.83]
 [ 9235.98  9361.33]
 [42441.73 22144.03]
 [38233.05 35491.64]
 [25557.72 19515.54]
 [15350.18 10107.22]
 [24280.04 23244.79]
 [ 7625.75  2789.06]
 [ 2221.22  2261.57]
 [12681.7  10594.5 ]
 [10482.7   9304.7 ]
 [10753.64 10435.07]
 [ 5778.51  4894.75]
 [14229.94 14313.85]
 [19553.88 28287.9 ]
 [10687.23 14426.07]
 [ 1626.74  1627.28]
 [12460.49 25517.11]
 [ 6495.56  6555.07]
 [39321.4  39611.76]
 [11131.19  9964.06]
 [ 9086.67  1720.35]
 [ 6154.78  2730.11]
 [ 8480.47  6500.24]
 [ 3253.34  2643.27]
 [ 5451.85  1719.44]
 [14138.31 11085.59]
 [11229.41 10115.01]
 [ 7762.43  4846.92]
 [13315.11 12982.87]
 [13196.04 28923.14]
 [10497.73  9391.35]
 [ 4236.3   4544.23]
 [ 9924.75 17128.43]
 [16365.74 13844.51]
 [ 7279.94  6113.23]
 [ 5258.45  4441.21]
 [ 2238.1   1633.96]
 [ 9754.98  4058.71]
 [ 7517.45  4435.09]
 [12906.04  8310.84]
 [ 2373.19  1986.93]
 [ 8899.03  4260.74]
 [ 9329.52  4504.66]
 [ 5253.82  4428.89]
 [ 7726.76  6117.49]
 [27936.18 30184.94]
 [ 1750.84  1708.93]
 [17937.43 11187.66]
 [ 6728.45  6796.86]
 [11472.14 11356.66]
 [ 4912.68  2498.41]
 [ 8477.83 27375.9 ]
 [28703.72 28101.33]
 [ 2494.04  2254.8 ]
 [ 3519.79  2597.78]
 [14304.29 14692.67]
 [12251.97 10370.91]
 [41850.76 41097.16]
 [ 5686.61  3981.98]
 [ 5382.97  5472.45]
 [24178.37 21223.68]
 [ 3223.13  2534.39]
 [ 4795.02  1972.95]
 [ 8870.77  6406.41]
 [ 7176.42  6551.75]
 [ 6503.76  4058.12]
 [ 4468.76  4243.59]
 [11817.13 11512.41]
 [46292.57 46889.26]
 [17188.77 12268.63]
 [18812.06 19199.94]
 [11736.72  4433.39]
 [43262.33 42969.85]
 [ 5691.45 23241.47]
 [10753.08  9140.95]
 [ 8042.98  5836.52]
 [ 1345.91  1149.4 ]
 [11688.88  8765.25]
 [13887.71 14043.48]
 [ 7778.02  5312.17]
 [ 6459.71 10795.94]
 [ 6538.81  6282.23]
 [ 6303.86  1969.61]
 [ 7442.52  6746.74]
 [ 7336.08  5354.07]
 [14252.85 14001.29]
 [ 6887.65  6877.98]
 [12425.19  6196.45]
 [ 7946.32  7986.48]
 [14250.98  8277.52]
 [ 4729.28  3206.49]
 [12881.1  11848.14]
 [14390.44 14210.54]
 [16899.77 12265.51]
 [11979.5  11837.16]
 [ 7352.02  6652.53]
 [ 4227.49  2137.65]
 [10991.88  1131.51]
 [ 9202.16  8342.91]
 [14330.21 12244.53]
 [ 6257.17  4561.19]
 [ 6666.93 17626.24]
 [ 7049.98  6875.96]
 [12990.82  9447.38]
 [34403.71 34254.05]
 [ 5861.83  6067.13]
 [14267.51 11729.68]
 [ 6785.49  5383.54]
 [37402.39 37465.34]
 [ 8176.09  7371.77]
 [ 8085.44  7325.05]
 [12888.39  8410.05]
 [10547.76 10461.98]
 [ 5185.76  3279.87]
 [ 9755.5   7727.25]
 [ 3019.5   2731.91]
 [ 6948.89  6858.48]
 [19332.93 19521.97]
 [46409.74 47305.31]
 [ 4983.8   3987.93]
 [ 3593.86  3238.44]
 [ 5263.96  7323.73]
 [ 1690.31  1704.57]
 [ 7777.96  7445.92]
 [ 2791.21  1629.83]
 [ 9315.65  4877.98]
 [ 9249.67  3561.89]
 [ 8878.76  8605.36]
 [26021.13 24520.26]
 [45835.53 45710.21]
 [15786.89 15019.76]
 [ 6650.56  6664.69]
 [11308.48 20709.02]
 [42589.86 40932.43]
 [10306.66  9500.57]
 [39275.   40182.25]
 [ 1672.91  1137.47]
 [37968.41 38511.63]
 [ 5169.2   4670.64]
 [12478.56 13019.16]
 [ 6831.82  4189.11]
 [39748.6  38709.18]
 [ 6472.29  5594.85]
 [ 9988.16 27346.04]
 [10738.49  9788.87]
 [ 4783.61  2362.23]
 [19051.08 13224.69]
 [12264.24 12222.9 ]
 [10512.28  4320.41]
 [14624.48 12731.  ]
 [14453.5   2203.47]
 [ 8227.4   6079.67]
 [ 4973.24  3591.48]
 [11746.13  8596.83]
 [21851.81 21771.34]
 [ 3579.02  2927.06]
 [ 1745.85  1708.  ]
 [10363.03  2803.7 ]
 [46837.56 48517.56]
 [10726.28  9282.48]
 [ 5475.98  4738.27]
 [16997.33 12269.69]
 [12640.82 11879.1 ]
 [34461.56 34166.27]
 [ 6899.5   6496.89]
 [ 5754.35  4751.07]
 [ 9421.53  8457.82]
 [ 2222.63  1639.56]
 [ 5807.84  2566.47]
 [22816.38 14455.64]
 [19303.62 16577.78]
 [14269.   13457.96]
 [ 2774.91  2721.32]
 [ 3249.07 18218.16]
 [11255.33  8615.3 ]
 [10173.24  9722.77]
 [14998.01 14283.46]
 [19726.66 21472.48]
 [ 9360.03  5972.38]
 [17086.08 14711.74]
 [ 2584.54  2128.43]
 [ 8720.15  5438.75]
 [ 7151.7   3935.18]
 [15452.83  8534.67]
 [ 3245.69 11884.05]
 [ 7692.35  6837.37]
 [47623.48 42983.46]
 [ 4022.47  3925.76]
 [ 7153.61 18903.49]
 [ 1992.63  2117.34]
 [11417.87  8283.68]
 [ 5595.84  3366.67]
 [15078.07 11833.78]
 [46387.28 47928.03]
 [17923.11 17361.77]
 [ 9414.59  9290.14]
 [44799.15 42560.43]
 [16075.95 13224.06]
 [11590.84  4433.92]
 [10097.48  9377.9 ]
 [ 5302.37  3597.6 ]
 [28912.9  29141.36]]

In [136]:
print(r2_score(y_test, y_pred_RF))
rmse=mean_squared_error(y_test, y_pred_RF)
print(np.sqrt(rmse))

0.8746818555383231
4441.779037407534